# Generated by Django 3.1.4 on 2020-12-28 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_corona_positive', models.BooleanField(default=False)),
                ('on_medications', models.BooleanField(default=False)),
                ('is_diabetic', models.BooleanField(default=False)),
                ('is_heart_patient', models.BooleanField(default=False)),
                ('has_applied', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient Profile')),
            ],
        ),
    ]
