# Generated by Django 3.1.4 on 2020-12-30 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_beds', models.IntegerField(default=30)),
                ('available_beds', models.IntegerField(default=30)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('applicants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.patient', verbose_name='Applicants')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=3.0)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.hospital', verbose_name='Hospital')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.patient', verbose_name='Patient')),
            ],
        ),
    ]
