# Generated by Django 3.1.4 on 2021-05-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20210502_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(max_length=8, null=True, unique=True),
        ),
    ]
