# Generated by Django 3.1.4 on 2021-05-19 04:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210518_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='has_applied',
            new_name='accepted',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='application',
            new_name='hospital',
        ),
        migrations.AddField(
            model_name='patient',
            name='documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='Documents/'), blank=True, null=True, size=None),
        ),
    ]
