# Generated by Django 3.1.4 on 2021-05-31 10:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210526_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='required_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), blank=True, null=True, size=None),
        ),
    ]
