# Generated by Django 3.1.4 on 2021-05-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20210531_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
