# Generated by Django 3.1.4 on 2021-06-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20210531_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='applied_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
