# Generated by Django 3.1.4 on 2021-06-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_patient_applied_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='documents',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='Documents/')),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.patient')),
            ],
        ),
    ]
