# Generated by Django 3.1.4 on 2021-06-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_hospital_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='required_documents',
        ),
    ]
