export const reviews = [
    {
       _id : '-MN7Jk1eosivUUOfUnZ1',
       city: 'Pune',
       feedback: 'Good Service',
       isp_Name: 'Hathway Cable and Datacom Pvt Ltd',
       locality: 'Erandwane',
       map_Latitude: '18.503198',
       map_Longitude: '73.8285357',
       overallRating: '4.0',
       priceRating: '2.0',
       reviewDate: '27/11/2020',
       serviceRating: '2.5',
       speedRating: '4.0',
       type: 'WiFi',
       userEmail: 'rkhan@gmail.com'
     },
     {
       _id : '-MN7cTjRW6k08RMMvo2w',
       city: 'Pune',
       feedback: 'Good',
       isp_Name: 'Bharti Airtel Ltd.',
       locality: 'Erandwane',
       map_Latitude: '18.5031986',
       map_Longitude: '73.8285353',
       overallRating: '4.0',
       priceRating: '4.0',
       reviewDate: '27/11/2020',
       serviceRating: '3.0',
       speedRating: '3.0',
       type: 'WiFi',
       userEmail: 'rkhan@gmail.com'
     },{
       _id : '-MNEMO2qPMWu6epVbkzp',
       city: 'Pune',
       feedback: 'Not Bad',
       isp_Name: 'Reliance Jio Infocomm Limited',
       locality: 'Erandwane',
       map_Latitude: '18.5031985',
       map_Longitude: '73.8285101',
       overallRating: '2.0',
       priceRating: '3.0',
       reviewDate: '28/11/2020',
       serviceRating: '3.5',
       speedRating: '3.5',
       type: 'WiFi',
       userEmail: 'rkhan@gmail.com'
     },{
       _id : '-MNKNCwZwsr9D8o4aKpM',
       city: 'Pune',
       feedback: 'Shitty',
       isp_Name: 'Vodafone Essar Limited-Value Added Services',
       locality: 'Erandwane',
       map_Latitude: '18.5032541',
       map_Longitude: '73.8286857',
       overallRating: '2.0',
       priceRating: '2.0',
       reviewDate: '30/11/2020',
       serviceRating: '4.0',
       speedRating: '2.0',
       type: 'Data',
       userEmail: 'dhoni11@gmail.com'
     },
     {
       _id : '-MNMpt05KhZY4FpNKUGf',
       city: 'Pune',
       feedback: 'Noice',
       isp_Name: 'Vodafone Essar Limited-Value Added Services',
       locality: 'Erandwane',
       map_Latitude: '18.5032026',
       map_Longitude: '73.8284788',
       overallRating: '5.0',
       priceRating: '3.0',
       reviewDate: '30/11/2020',
       serviceRating: '2.0',
       speedRating: '4.0',
       type: 'Data',
       userEmail: 'rkhan@gmail.com'
     }
]