# Generated by Django 3.1.4 on 2021-05-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210508_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='participants',
            new_name='user',
        ),
    ]
